name: update awesome-stars

on:
  workflow_dispatch:
  schedule:
    # * must be quoted in YAML cron strings → docs.github.com
    - cron: '30 0 * * *'

permissions:          # grant the token once for the entire workflow
  contents: write

jobs:
  awesome-stars:
    name: Update awesome-stars
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4   # v4 = latest

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install starred
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir starred

      - name: Derive repository name
        run: echo "REPOSITORY_NAME=${GITHUB_REPOSITORY#*/}" >> "$GITHUB_ENV"

      - name: Update README (by topic_limit 3)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
          REPOSITORY: ${{ env.REPOSITORY_NAME }}
        run: |
          starred \
            --username "$USERNAME" \
            --repository "$REPOSITORY" \
            --sort \
            --topic \
            --topic_limit 1 \
            --filename README.md \
            --token "$GITHUB_TOKEN" \
            --message 'awesome-stars: topic_limit 3 refresh via Actions'

      - name: Update languages.md (by language)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
          REPOSITORY: ${{ env.REPOSITORY_NAME }}
        run: |
          starred \
            --username "$USERNAME" \
            --repository "$REPOSITORY" \
            --sort \
            --token "$GITHUB_TOKEN" \
            --filename languages.md \
            --message 'awesome-stars: languages refresh via Actions'

      - name: Update topics.md (by topic)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
          REPOSITORY: ${{ env.REPOSITORY_NAME }}
        run: |
          starred \
            --username "$USERNAME" \
            --repository "$REPOSITORY" \
            --sort \
            --topic \
            --topic_limit 500 \
            --filename topics.md \
            --token "$GITHUB_TOKEN" \
            --message 'awesome-stars: topics refresh via Actions'
